name: Security Scan

on:
  push: # Trigger on pushes to any branch
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: read

jobs:
  scan:
    uses: khangvum/workflows/.github/workflows/gitleaks.yml@main
    secrets: inherit
